### ISSUE TITLE
Serve hugo-generated page for xmpp.org/rfcs 

### ISSUE THREAD

**Issue by wurstsalat3000** [xsf/infrastructure#15]
Currently https://xmpp.org/rfcs redirects to https://xmpp.org/rfcs/, which is a directory listing.

In xsf/xmpp.org#975 I built a new index page for `xmpp.org/rfcs`. In order to make this work correctly, we would need a server direction for `xmpp.org/rfcs`. Since xmpp.org serves some RFC files itself (e.g. https://xmpp.org/rfcs/rfc3920.html), and it should continue to do so, we would need an exact match directive for that (and only that URL), I think.

**Comment by mwild1** [comment]
Done. Actually note that the hugo container is redirecting `/rfcs` -> `/rfcs/` so it wasn't enough to just make that URL work.

The current rule in place will proxy `/rfcs/` but not `/rfcs/*`. The only quirk here is if someone linked to `/rfcs/index.html` they'll get a 404 instead of seeing the index.html served by Hugo. I think this is fine...

Hopefully nothing else broke (I did a quick test), but I guess we'll hear if it did :)
